use bash bc & printf to calculate ratios for pictures

diff --git a/scripts/vimg b/scripts/vimg
--- a/scripts/vimg
+++ b/scripts/vimg
@@ -8,6 +8,32 @@ declare -x PREVIEW_ID="preview"
 declare -x TMP_FOLDER="/tmp/vimg"
 mkdir -p $TMP_FOLDER
 
+function calculate_size {
+  if ! command -v bc &> /dev/null; then
+    echo "the basic unix tool bc (basic calculator) could not be found in your path,\nplease install it to display media content"
+    exit
+  fi
+
+  # grab vars
+  max_width="${1}"
+  max_height="${2}"
+  img_width="${3}"
+  img_height="${4}"
+  img_stretch="${5}"
+
+  # image width times a multiplier since in most terminals the line height is bigger than the mono-spaced character width
+  stretched_width=$(echo "scale=20; ${img_width} * (${img_stretch} / 100)" | bc)
+
+  width_ratio=$(echo "scale=20; ${max_width} / ${stretched_width}" | bc)
+  height_ratio=$(echo "scale=20; ${max_height} / ${img_height}" | bc)
+  both_ratios=("${width_ratio}" "${height_ratio}")
+  best_ratio=$(printf "%.20f\n" "${both_ratios[@]}" | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n | head -n 1)
+
+  new_width=$(echo "${stretched_width} * ${best_ratio}" | bc)
+  new_height=$(echo "${img_height} * ${best_ratio}" | bc)
+  echo "$(printf "%.0f" "$new_width") $(printf "%.0f" "$new_height")"
+}
+
 function render_at_size {
   if ! command -v identify &> /dev/null; then
     echo "identify (part of imagemagick) could not be found in your path,\nplease install it to display media content"
@@ -23,9 +49,8 @@ function render_at_size {
   img_width=$(identify -format "%w" "${img_path}")
   img_height=$(identify -format "%h" "${img_path}")
 
-  # Get dimensions from lua script and push them into an array
-  scripts_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
-  local raw_dimensions=$(lua "${scripts_dir}/calc_image_size.lua" "${max_width}" "${max_height}" "${img_width}" "${img_height}" "${img_stretch}")
+  # Get dimensions from and push them into an array
+  local raw_dimensions=$(calculate_size "${max_width}" "${max_height}" "${img_width}" "${img_height}" "${img_stretch}")
   dimensions=($raw_dimensions)
   new_width="${dimensions[0]}"
   new_height="${dimensions[1]}"
