break: Replace UEBERZUG with Chafa. (#35)
* Replace UEBERZUG with Viu.

Viu is a bit different and works a bit different than ueberzug, but it
seems to do a nice job.

I managed to get everything working on my Macbook too (i'll include a
movie in the pull request)

Some limitations:
I didn't really know how that FIFO system worked, but I figure it was
used to not make the terminal preview window go haywire on reloads
(drawing lines and clearing the screen). So I have left GIFs unanimated
(it is an out-of-the-box feature of VIU though)

On Linux (given that you aren't running inside tmux the images will look
nice and crisp, in tmux and on OSX the images are instead rendered to
block-maps.. looks a bit worse, but still fairly usable)

Note one:
It's worth mentioning that the previous version (with ueberzug) used
imagemagick in gifs to find frames and convert frames to images.
I thought about adding docs for it, but I'm not generating stills
through scripting anymore. Make sure to add the requirement to
imagemagick to the docs if generating stills becomes a thing again ;)

Note two:
the next upcoming verison of viu allows x & y offset, but that release
is still in the works. So i haven't included it in this pull request. I
might create a new pull request to re-add the offset in a few weeks.
Until then I think it's okay to keep that info around when we call the
vimg script.

Thanks for looking at this pull and thanks for the amazing work on this
plugin!

* Revert to always render as blocks

It looks like Iterm and a bunch of Linux terminals end up showing black
screens, so I'm reverting to always render with blocks instead.

* Add handy installation instructions

* automatically resize images to fit

* use bash bc & printf to calculate ratios for pictures

* clean up last comments

* save file as png

* Add svg support

* replace viu with CHAFA as it has much better image quality

diff --git a/scripts/vimg b/scripts/vimg
--- a/scripts/vimg
+++ b/scripts/vimg
@@ -1,117 +1,75 @@
 #!/bin/bash
 
-case $(uname) in
- Darwin)
-     echo "Not supported"
-     exit
-	;;
-esac
-
 SCRIPT=`realpath $0`
 
 readonly BASH_BINARY="$(which bash)"
-declare -x UEBERZUG_FIFO="$(mktemp --dry-run --suffix "vimg-$$-ueberzug")"
 declare -x PREVIEW_ID="preview"
 
 declare -x TMP_FOLDER="/tmp/vimg"
 mkdir -p $TMP_FOLDER
 
-function start_ueberzug {
-    mkfifo "${UEBERZUG_FIFO}"
+function render_at_size {
+  max_width="${1}"
+  max_height="${2}"
+  img_path="${3}"
 
-    tail --follow "$UEBERZUG_FIFO" | ueberzug layer --silent --parser bash &
+  # animation is turned off as it does werid things with the terminal output
+  chafa --animate=off --center=on --clear --size "${max_width}x${max_height}" "${img_path}"
 }
-
-function finalise {
-    3>&- \
-        exec
-    &>/dev/null \
-        rm "${UEBERZUG_FIFO}"
-    &>/dev/null \
-        kill $(jobs -p)
-}
-
 
 function draw_preview {
+    if ! command -v chafa &> /dev/null; then
+      echo "chafa could not be found in your path,\nplease install it to display media content"
+      exit
+    fi
 
     if [[ "$1" == "imagepreview" ]]; then
-        >"${UEBERZUG_FIFO}" declare -A -p cmd=( \
-            [action]=add [identifier]="${PREVIEW_ID}" \
-            [x]="${3}" [y]="${4}" \
-            [width]="${5}" [height]="${6}" \
-            [path]="${2}")
+      render_at_size "${5}" "${6}" "${2}" "${7}"
+      # viu -b -w ${5} -h ${6} "${2}"
 
     elif [[ "$1" == "gifpreview" ]]; then
-        file="${2##*/}"
-        path="${PWD}/$2"; path="${path// /_}"; path="${path//\//_}" #replace space and / into _
-        path="${TMP_FOLDER}/${path}"
-
-        echo -ne "Loading preview... 0%\r"
-        frame_total=$(identify -format "%n\n" $2 | head -1)
-        IFS=$'\n' read -r -d '' -a ticks < <(identify -format "%T\n" $2 && printf '\0'); unset IFS
-        [[ $(ls ${path}/ 2>/dev/null | wc -l) -ne $frame_total ]] \
-          && (mkdir -p ${path} && convert -coalesce -resize 720x480\> "$2" "${path}/${file}.png"&disown)
-
-        frame_index=0
-        while true; do
-          frame_extracted=$(ls -1 ${path}/ 2>/dev/null| wc -l)
-          if [[ $frame_extracted -lt $frame_total ]]; then
-            echo -ne "Loading preview... $((frame_extracted*100/frame_total))%\r"
-          else
-            echo -ne "                     \r"
-            >"${UEBERZUG_FIFO}" declare -A -p cmd=( \
-                [action]=add [identifier]="${PREVIEW_ID}" \
-                [x]="${3}" [y]="${4}" \
-                [width]="${5}" [height]="${6}" \
-                [path]="${path}/${file}-${frame_index}.png")
-            delay=$(bc <<< "scale=2; ${ticks[$frame_index]}/100") # 1 tick == 1/100s
-            sleep $delay
-          fi
-          frame_index=$((frame_index + 1))
-          [[ $frame_index -ge $frame_total ]] && frame_index=0
-        done
+      # This is static for now, feel free to re-introduce FIFO to make
+      # animations work again, plaing viu gifs (removing the -s flag) causes
+      # the preview window to scroll weirdly
+      render_at_size "${5}" "${6}" "${2}" "${7}"
 
     elif [[ "$1" == "videopreview" ]]; then
-        path="${2##*/}"
-        echo -e "Loading preview..\nFile: $path"
-        ffmpegthumbnailer -i "$2" -o "${TMP_FOLDER}/${path}.png" -s 0 -q 10
-        >"${UEBERZUG_FIFO}" declare -A -p cmd=( \
-            [action]=add [identifier]="${PREVIEW_ID}" \
-            [x]="${3}" [y]="${4}" \
-            [width]="${5}" [height]="${6}" \
-            [path]="${TMP_FOLDER}/${path}.png")
+      if ! command -v viu &> /dev/null; then
+        echo "ffmpegthumbnailer could not be found in your path,\nplease install it to display video previews"
+        exit
+      fi
+      path="${2##*/}"
+      echo -e "Loading preview..\nFile: $path"
+      ffmpegthumbnailer -i "$2" -o "${TMP_FOLDER}/${path}.png" -s 0 -q 10
+      clear
+      render_at_size "${5}" "${6}" "${TMP_FOLDER}/${path}.png" "${7}"
 
     elif [[ "$1" == "pdfpreview" ]]; then
-        path="${2##*/}"
+      path="${2##*/}"
         echo -e "Loading preview..\nFile: $path"
-        [[ ! -f "${TMP_FOLDER}/${path}.png" ]] && pdftoppm -png -singlefile "$2" "${TMP_FOLDER}/${path}"
-        >"${UEBERZUG_FIFO}" declare -A -p cmd=( \
-            [action]=add [identifier]="${PREVIEW_ID}" \
-            [x]="${3}" [y]="${4}" \
-            [width]="${5}" [height]="${6}" \
-            [path]="${TMP_FOLDER}/${path}.png")
-
+        [[ ! -f "${TMP_FOLDER}/${path}.png" ]] && pdftoppm -png -singlefile "$2" "${TMP_FOLDER}/${path}.png"
+        clear
+        render_at_size "${5}" "${6}" "${TMP_FOLDER}/${path}.png" "${7}"
     fi
 }
-
 
 function parse_options {
     extension="${1##*.}"
     case $extension in
-    jpg | png | jpeg | webp)
-        draw_preview  imagepreview "$1" $2 $3 $4 $5
+    jpg | png | jpeg | webp | svg)
+        draw_preview  imagepreview "$1" $2 $3 $4 $5 $6
     ;;
 
     gif)
-        draw_preview  gifpreview "$1" $2 $3 $4 $5
+        draw_preview  gifpreview "$1" $2 $3 $4 $5 $6
     ;;
 
     avi | mp4 | wmv | dat | 3gp | ogv | mkv | mpg | mpeg | vob |  m2v | mov | webm | mts | m4v | rm  | qt | divx)
-        draw_preview  videopreview "$1" $2 $3 $4 $5
+        draw_preview  videopreview "$1" $2 $3 $4 $5 $6
     ;;
 
     pdf | epub)
-        draw_preview  pdfpreview "$1" $2 $3 $4 $5
+        draw_preview  pdfpreview "$1" $2 $3 $4 $5 $6
     ;;
 
     *)
@@ -120,10 +78,5 @@ function parse_options {
     esac
 }
 
-
-
-
-trap finalise EXIT
-start_ueberzug
 parse_options "${@}"
 read
